### ISSUE TITLE
Partial Missing Error - Can't sync or edit feed

### ISSUE THREAD

**Issue by Humni** [LukeTowers/oc-easyfacebookfeed-plugin#8]
I'm getting an error when I try to edit/view an existing feed. I want to trigger manual sync but this error is currently blocking me. This wasn't occurring before I updated the site. Unsure what versions changed as it hadn't been updated in a couple of months. 

The error I'm getting is this:

```
October\Rain\Exception\SystemException: The partial '_field_sensitive.htm' is not found. in /modules/system/traits/ViewMaker.php:91
```

Stacktrace: 

```
#0 /modules/backend/widgets/Form.php(275): Backend\Classes\WidgetBase->makePartial('_field_sensitiv...', Array)
#1 /modules/backend/widgets/form/partials/_field.htm(22): Backend\Widgets\Form->renderFieldElement(Object(Backend\Classes\FormField))
#2 /modules/system/traits/ViewMaker.php(247): include('/var/www/...')
#3 /modules/system/traits/ViewMaker.php(97): Backend\Classes\WidgetBase->makeFileContents('/var/www/...', Array)
#4 /modules/backend/widgets/form/partials/_field-container.htm(8): Backend\Classes\WidgetBase->makePartial('_field.htm', Array)
#5 /modules/system/traits/ViewMaker.php(247): include('/var/www/...')
#6 /modules/system/traits/ViewMaker.php(97): Backend\Classes\WidgetBase->makeFileContents('/var/www/...', Array)
#7 /modules/backend/widgets/form/partials/_form_fields.htm(2): Backend\Classes\WidgetBase->makePartial('_field-containe...', Array)
#8 /modules/system/traits/ViewMaker.php(247): include('/var/www/...')
#9 /modules/system/traits/ViewMaker.php(97): Backend\Classes\WidgetBase->makeFileContents('/var/www/...', Array)
#10 /modules/backend/widgets/form/partials/_form_tabs.htm(52): Backend\Classes\WidgetBase->makePartial('_form_fields.ht...', Array)
#11 /modules/system/traits/ViewMaker.php(247): include('/var/www/...')
#12 /modules/system/traits/ViewMaker.php(97): Backend\Classes\WidgetBase->makeFileContents('/var/www/...', Array)
#13 /modules/backend/widgets/form/partials/_section.htm(26): Backend\Classes\WidgetBase->makePartial('_form_tabs.htm', Array)
#14 /modules/system/traits/ViewMaker.php(247): include('/var/www/...')
#15 /modules/system/traits/ViewMaker.php(97): Backend\Classes\WidgetBase->makeFileContents('/var/www/...', Array)
#16 /modules/backend/widgets/form/partials/_form.htm(7): Backend\Classes\WidgetBase->makePartial('_section.htm', Array)
#17 /modules/system/traits/ViewMaker.php(247): include('/var/www/...')
#18 /modules/system/traits/ViewMaker.php(97): Backend\Classes\WidgetBase->makeFileContents('/var/www/...', Array)
#19 /modules/backend/widgets/form/partials/_form-container.htm(8): Backend\Classes\WidgetBase->makePartial('_form.htm')
#20 /modules/system/traits/ViewMaker.php(247): include('/var/www/...')
#21 /modules/system/traits/ViewMaker.php(97): Backend\Classes\WidgetBase->makeFileContents('/var/www/...', Array)
#22 /modules/backend/widgets/Form.php(228): Backend\Classes\WidgetBase->makePartial('_form-container...', Array)
#23 /modules/backend/behaviors/FormController.php(419): Backend\Widgets\Form->render(Array)
#24 [internal function]: Backend\Behaviors\FormController->formRender()
#25 /vendor/october/rain/src/Extension/ExtendableTrait.php(414): call_user_func_array(Array, Array)
#26 /modules/backend/classes/Controller.php(184): Backend\Classes\Controller->extendableCall('formRender', Array)
#27 /plugins/luketowers/easyfacebookfeed/controllers/feeds/update.htm(13): Backend\Classes\Controller->__call('formRender', Array)
#28 /modules/system/traits/ViewMaker.php(247): include('/var/www/...')
#29 /modules/system/traits/ViewMaker.php(109): Backend\Classes\Controller->makeFileContents('/var/www/...')
#30 /modules/backend/classes/Controller.php(419): Backend\Classes\Controller->makeView('update')
#31 /modules/backend/classes/Controller.php(296): Backend\Classes\Controller->execPageAction('update', Array)
#32 /modules/backend/classes/BackendController.php(165): Backend\Classes\Controller->run('update', Array)
#33 [internal function]: Backend\Classes\BackendController->run('luketowers/easy...')
#34 /vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#35 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#36 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Backend\Classes\BackendController), 'run')
#37 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#38 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#39 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /modules/backend/classes/BackendController.php(68): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(131): Backend\Classes\BackendController->Backend\Classes\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#42 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(68): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#60 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#61 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#62 /vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#63 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#64 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#65 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(25): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#70 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#71 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#72 /index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#73 {main}
```

**Comment by addoklopman** [comment]
Same here, I get this error to. Have you found a fix yet?

**Comment by addoklopman** [comment]
I think it should be type: password in plugins/luketowers/easyfacebookfeed/models/feed/fields.yaml

**Comment by addoklopman** [comment]
That fixed it for me. Don't know if luke had some custom functionality in mind with type: sensitive

**Comment by SplicedWeb** [comment]
> I think it should be type: password in plugins/luketowers/easyfacebookfeed/models/feed/fields.yaml

Thanks, this helped for me too.
